# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: 'ElecFreaks Learn-en'
site_description: 'ElecFreaks Product Document'
site_author: 'Will'
site_url: 'https://www.elecfreaks.com/learn-en/'

# Repository
repo_name: 'Microbit'
repo_url: 'https://github.com/elecfreaks/learn-en'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 ElecFreaks'

# Theme directory
theme_dir: material

# Icon
#site_favicon: 'docs/images/favicon.ico'
site_favicon: https://raw.githubusercontent.com/elecfreaks/learn-en/master/docs/images/favicon.ico

# Configuration
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: light green
    accent: 'indigo'    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/elecfreaks/learn-en'
    - type: 'facebook'
      link: 'https://www.facebook.com/ElecFreaksTech/'
    #- type: 'linkedin'
    #  link: 'https://linkedin.com/in/squidfunk'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.keys

# Page tree
pages:
  - ElecFreaks Learn: 'index.md'
  - micro:bit Basic Tutorial:
    - BBC micro:bit: micro_bit.md
    - micro:bit Funny Classroom Series:
      - Flashing Heart: classroom_case_01.md
      - Smiley Buttons: classroom_case_02.md
      - Love Meter: classroom_case_03.md
      - Rock Papaer Scissors: classroom_case_04.md
      - Magic Button Trick: classroom_case_05.md
      - Coin Flipper: classroom_case_06.md
      - Salute: classroom_case_07.md
      - Hack your headphones: classroom_case_08.md
      - Banana Keyboard: classroom_case_09.md
      - Guitar: classroom_case_10.md
      - Duct Type Wallet: classroom_case_11.md
      - Watch: classroom_case_12.md
      - Countdown Timer: classroom_case_13.md
      - Digital Watch: classroom_case_14.md
      - Soil Moisture: classroom_case_15.md
      - Plant Watering: classroom_case_16.md
      - Reaction Time: classroom_case_17.md
      - States of Matter: classroom_case_18.md
      - Mood Radio: classroom_case_19.md
      - Tele-Potato: classroom_case_20.md
      - Hot or Cold: classroom_case_21.md
      - Voting Machine: classroom_case_22.md
      - Infection: classroom_case_23.md
      - Fireflies: classroom_case_24.md
      - Rock Paper Scissors Teams: classroom_case_25.md
      - Microcoin: classroom_case_26.md
      - Inchworm: classroom_case_27.md
      - Milk Monster: classroom_case_28.md
      - RC Car: classroom_case_29.md
      - Timing Gates: classroom_case_30.md
      - Compass: classroom_case_31.md
      - Telegraph: classroom_case_32.md
      - Railway Crossing: classroom_case_33.md
      - Karel: classroom_case_34.md

  - micro:bit relevant materials:
    - Edge Connector Data Sheet: Edge_Connector_Data_Sheet.md
    - How to Use Bluetooth(IOS System): How_to_Use_Bluetooth_IOS_System.md
    - troubleshooting downloads with webusb: troubleshooting_downloads_with_webusb.md
    - ring:bit car v2 accelerometer arithmetic: ring_bit_car_v2_accelerometer_arithmetic.md
    - Excel and micro:bit: 


  - micro:bit Kits:
    - micro:bit Watch Kit:
      - Introduction: watch_kit.md
      - Power:bit Introduction: power_bit.md
      - case 01：Compass: watch_kit_case_01.md
      - case 02：Dice: watch_kit_case_02.md
      - case 03：Thermometer: watch_kit_case_03.md
      - case 04：Timer: watch_kit_case_04.md
      - case 05：Flashlight: watch_kit_case_05.md   
    - micro:bit Basic Kit:
      - Introduction: basic_kit.md
      - Basic:bit Introduction: basic_bit.md
      - case 01 Light Controller: basic_kit_case_01.md
      - case 02 Morse Code: basic_kit_case_02.md
      - case 03 Function Selector: basic_kit_case_03.md
      - case 04 Show Box for Stickers: basic_kit_case_04.md
      - case 05 Shock Box: basic_kit_case_05.md

    - micro:bit Starter Kit:
      - Introduction: starter_kit.md
      - Breadboard:bit Introduction: breadboard_bit.md
      - Lesson 01 LED: starter_kit_case_01.md
      - Lesson 02 Button: starter_kit_case_02.md
      - Lesson 03 Trimpot: starter_kit_case_03.md
      - Lesson 04 Photocell: starter_kit_case_04.md
      - Lesson 05 RGB LED: starter_kit_case_05.md
      - Lesson 06 Self-lock Switch: starter_kit_case_06.md
      - Lesson 07 Temperature Sensor: starter_kit_case_07.md
      - Lesson 08 Servo: starter_kit_case_08.md
      - Lesson 09 Buzzer: starter_kit_case_09.md
      - Lesson 10 Motor: starter_kit_case_10.md
      - Lesson 11 Rainbow LED: starter_kit_case_11.md
      - Lesson 12 Accelerometer: starter_kit_case_12.md
      - Lesson 13 Compass: starter_kit_case_13.md
      - Lesson 14 Ambient Light: starter_kit_case_14.md

    - micro:bit Tinker Kit: 
      - Introduction: tinker_kit.md
      - Octopus:bit Introduction: octopus_bit.md
      - case 01 Music Machine: tinker_kit_case_01.md
      - case 02 Smart Light: tinker_kit_case_02.md
      - case 03 Electro-Theremin: tinker_kit_case_03.md
      - case 04 Simple Alarm Box: tinker_kit_case_04.md
      - case 05 Plant Monitoring Device: tinker_kit_case_05.md
      - case 06 Intruder Detection: tinker_kit_case_06.md
      - case 07 Fish Feeder: tinker_kit_case_07.md
      - case 08 Motion Detector: tinker_kit_case_08.md
      - case 09 Lie Detector: tinker_kit_case_09.md
      - case 10 PADDLEBALLSUPERSMASHEM: tinker_kit_case_10.md
      - case 11 Avoid Asteroids: tinker_kit_case_11.md
      - case 12 Remote Control Everything: tinker_kit_case_12.md
      - case 13 micro:bit Car: tinker_kit_case_13.md
      - case 14 Flipping Pancakes: tinker_kit_case_14.md
      - case 15 Maze Runner: tinker_kit_case_15.md
      - case 16 QUICK MATHS: tinker_kit_case_16.md
      - case 17 Pitch Perfect: tinker_kit_case_17.md
      - case 18 Finger Dexterity: tinker_kit_case_18.md
      - case 19 Electric Spirit Level: tinker_kit_case_19.md
      - case 20 Space Shooter: tinker_kit_case_20.md
      - case 21 Flappy Bird: tinker_kit_case_21.md
      - case 22 Wire Transmission: tinker_kit_case_22.md
      - case 23 Snake Game: tinker_kit_case_23.md
      - case 24 Game bit: tinker_kit_case_24.md
      - case 25 µ reMorse: tinker_kit_case_25.md
      - case 26 Coin Sorter with micro:bit: tinker_kit_case_26.md
      - case 27 Make a Waving Fortune Cat: tinker_kit_case_27.md
      - case 28 Put together the Krazy Kar v2: tinker_kit_case_28.md
      - case 29 Shoot Em Up Kit: tinker_kit_case_29.md
      - case 30 Reaction Time Tester: tinker_kit_case_30.md
      - case 31 morse code transmitter: tinker_kit_case_31.md
      - case 32 reclusebot: tinker_kit_case_32.md
      - case 33 access denied: tinker_kit_case_33.md
      - case 34 micropython: tinker_kit_case_34.md
      - case 35 build your own microbit security Door: tinker_kit_case_35.md

    - micro:bit Smart home Kit:
      - Introduction: smart_home_kit.md
      - sensor:bit Introduction: sensor_bit.md
      - case 01 Voice-activated Lights: smart_home_case_01.md
      - case 02 Smart Fan: smart_home_case_02.md
      - case 03 Auto Windows: smart_home_case_03.md
      - case 04 Smart Wardrobe: smart_home_case_04.md
      - case 05 Water Level Alarming: smart_home_case_05.md
      - case 06 smart telecontrol door opener: smart_home_case_06.md
      - case 07 smart decibel tester: smart_home_case_07.md
      - case 08 simple spirometer: smart_home_case_08.md
      - case 09 lie detector: smart_home_case_09.md
      - case 10 simple alarm box: smart_home_case_10.md
      - case 11 intruder detection system: smart_home_case_11.md

    - micro:bit experiment box kit:
      - introduction: experiment_box.md
      - circuit knowledge: experiment_box_circuit_knowledge.md
      - case 01 led: experiment_box_case_01.md
      - case 02 button: experiment_box_case_02.md
      - case 03 RGB led: experiment_box_case_03.md
      - case 04 trimpot: experiment_box_case_04.md
      - case 05 photocell: experiment_box_case_05.md
      - case 06 NTC: experiment_box_case_06.md
      - case 07 buzzer: experiment_box_case_07.md
      - case 08 servo: experiment_box_case_08.md
      - case 09 self-locking button: experiment_box_case_09.md
      - case 10 rainbow led ring: experiment_box_case_10.md
      - case 11 DC motor: experiment_box_case_11.md
      - circuit design 01: experiment_box_circuit_case_01.md
      - circuit design 02: experiment_box_circuit_case_02.md

    - ring:bit Car Kit: 
      - Introduction: ring_bit_car.md
      - Ring:bit Introduction: ring_bit.md
      - case 01 Add Package: ring_bit_car_case_01.md
      - case 02 S Walk: ring_bit_car_case_02.md
      - case 03 Draw a Circel: ring_bit_car_case_03.md
      - case 04 Wireless Remote Control: ring_bit_car_case_04.md
      - case 05 Crazy dance: ring_bit_car_case_05.md
      - case 06 Turns over Detection: ring_bit_car_case_06.md
      - case 07 Light Follow: ring_bit_car_case_07.md
      - case 08 Remote Control by an accelerometer: ring_bit_car_case_08.md

    - ring:bit Car Kit V2: 
      - Introduction: ring_bit_car_v2.md
      - Ring:bit Car Assembly Step: ring_bit_car_v2_assembly_step.md
      - Ring:bit Introduction: ring_bit_v2.md
      - Ring:bit Introduction of E-blocks: ring_bit_car_v2_extensions.md
      - line flow module: ring_bit_car_v2_line_flow_module.md
      - Rainbow LED module: ring_bit_car_v2_Rainbow_LED_module.md
      - case 01 Full speed ahead: ring_bit_car_v2_case_01.md
      - case 02 Make a shape: ring_bit_car_v2_case_02.md
      - case 03 Turn at an angle: ring_bit_car_v2_case_03.md
      - case 04 Here comes the police: ring_bit_car_v2_case_04.md
      - case 05 Crazy dance: ring_bit_car_v2_case_05.md
      - case 06 Remote Control: ring_bit_car_v2_case_06.md
      - case 07 Turns over Detection : ring_bit_car_v2_case_07.md
      - case 08 Light Follow: ring_bit_car_v2_case_08.md
      - case 09 Remote Control by an accelerometer: ring_bit_car_v2_case_09.md

    - motor:bit Smart Car Kit: 
      - Introduction: motor_bit_smart_car.md
      - motor:bit Introduction: motor_bit_v16.md
      - case 01 Fixed Parking: motor_bit_smart_car_case_01.md
      - case 02 Keep Distance: motor_bit_smart_car_case_02.md
      - case 03 Line Tracking: motor_bit_smart_car_case_03.md
      - case 04 Avoid Barrier: motor_bit_smart_car_case_04.md
      - case 05 Remote Control: motor_bit_smart_car_case_05.md
      - case 06 Bluetooth Control: motor_bit_smart_car_case_06.md  

    - robit Smart Car kit: 
      - Kit Introduction: robit_smart_car.md
      - mbot Introduction(robit): robit.md
      - robit Smart Car kit case01:ultrasonic measurement: robit_smart_car_case_01.md
      - robit Smart Car kit case02:line follow: robit_smart_car_case_02.md

    - Smart Science IoT Kit:
      - iot:kit: iot_kit.md
      - iot:bit: iot_bit.md
      - How to use thinkspeak: how_to_use_thinkspeak.md
      - How to use IFTTT: how_to_use_IFTTT.md
      - iot:kit case01: IOT_bit_case01.md
      - iot:kit case02: IOT_bit_case02.md
      - iot:kit case03: IOT_bit_case03.md
      - iot:kit case04: IOT_bit_case04.md
      - iot:kit case05: IOT_bit_case05.md

  - micro:bit Modules:
    - mbot Introduction(robit): 
      - robit Introduction: robit.md
      - case 01 Ultrasonic Distance Measurement: robit_case_01.md
      - case 02 Ultrasonic Obstacle Avoidance: robit_case_02.md
      - case 03 Never Fallen Car: robit_case_03.md
      - case 04 Line Tracking: robit_case_04.md
      - case 05 Reversing Alarm: robit_case_05.md
      - case 06 Rainbow LED: robit_case_06.md
      - case 07 Smart Car Light: robit_case_07.md
      - case 08 Bluetooth remote control: robit_case_08.md
      - case 09 Reaction test game: robit_case_09.md
    - sensor:bit: sensor_bit.md
    - motor:bit v14: motor_bit_v14.md
    - joystick:bit v2: joystick_bit_v2.md
    - iot:bit: iotbit.md
    - edge:bit: edge_bit.md
    - joystick:bit: joystick_bit.md
    - Power Supply: microbit_power_supply.md
    - christmas tree rainbow led: christmas_tree_rainbow_led.md
    - snowflake buzzer: snowflake_buzzer.md      
    - 3V vertical water pump: 3V_vertical_water_pump.md

  - micro:bit Octopus:
    - Input: 
      - Analog Rotation Brick: octopus_ef04085.md
      - OBPushButton - Blue: octopus_ef04034.md   
      - Octopus Analog Rotation Brick OBARot: octopus_ef04041.md   
      - Octopus Linear Slider Potentiometer Brick: octopus_ef04061.md
      - Octopus ADKeypad: octopus_ef04017.md   
      - Octopus Push Lock E-Switch Brick OBPLock: octopus_ef04035.md   
    - Output:
      - Octopus Single RGB Rainbow LED: octopus_ef04091.md
      - 3V Relay Module: octopus_ef04086.md
      - 8x16 matrix module: octopus_ef03418.md
      - OCTOPUS 1Channel Relay - 5V: octopus_ef04026.md   
      - Christmas Tree Rainbow LED for micro:bit: christmas_tree_rainbow_led.md
      - Snowflake Buzzer for micro:bit: snowflake_buzzer.md
      - IIC OLED Module: octopus_ef03155.md
      - Octopus Active Buzzer Brick OBAB02: octopus_ef04030.md   
      - Octopus Passive buzzer Brick OBPB01: octopus_ef04031.md   
      - Octopus 5mm LED Brick OBLED - Blue: octopus_ef04036.md
      - Octopus 5mm LED Brick - Green: octopus_ef04062.md
      - Octopus 5mm LED Brick - Red: octopus_ef04063.md
      - Octopus 5mm LED Brick - White: octopus_ef04065.md
      - Octopus 5mm LED Brick - Yellow: octopus_ef04066.md
      - Octopus Motor Brick: octopus_ef04059.md   
      - OCTOPUS Vibration Motor: octopus_ef04074.md
    - Sensor:
      - sonar:bit: sonar_bit.md
      - BME280 Air Pressure Sensor: octopus_ef04087.md
      - Octopus PM2.5 module: octopus_ef04090.md    
      - Octopus 2 Channel Tracking Module: octopus_ef04088.md   
      - Octopus Tilt Sensor: octopus_ef04001.md   
      - Octopus Hunt Sensor: octopus_ef04002.md    
      - Octopus Real-time Clock: octopus_ef04005.md   
      - Octopus Sound Sensor: octopus_ef04008.md   
      - Octopus Touch PAD Sensor: octopus_ef04011.md 
      - Octopus Photo Interrupter Sensor: octopus_ef04012.md
      - Octopus Crash Sensor Brick: octopus_ef04013.md   
      - Octopus Vibration Sensor: octopus_ef04014.md
      - Octopus MAX6675 Module: octopus_ef04018.md        
      - Octopus Temperature And Humidity Sensor: octopus_ef04019.md   
      - Octopus Rain/Steam Sensor: octopus_ef04024.md   
      - Octopus Soil Moisture Sensor Brick: octopus_ef04027.md   
      - Octopus Analog Photocell Brick OBPhotocell: octopus_ef04032.md   
      - Octopus Analog Voltage Divider Brick OBVoltage: octopus_ef04039.md   
      - Octopus DS18B20 Digital Temperature Brick: octopus_ef04042.md  
      - Octopus PIR Sensor Brick: octopus_ef04055.md   
      - Octopus Magnetic Switch: octopus_ef04075.md
      - Octopus Gesture Sensor Brick: octopus_ef04078.md
      - Octopus Temperature Sensor Brick TMP36 : octopus_ef04079.md
      - Octopus Analog Noise Sound Sensor Detection Module: octopus_ef04081.md
      - Octopus Wind Speed Sensor Anemometer Three Aluminium Cups: octopus_ef04083.md
      - Octopus Analog Photocell Brick Adjustable Sensitivity: octopus_ef10044.md
      - Octopus Dust Sensor Detector Module with Sharp GP2Y1010AU0F: octopus_ef11083.md

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
