# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: 'ElecFreaks Learn-en'
site_description: 'ElecFreaks Product Document'
site_author: 'Will'
site_url: 'https://www.elecfreaks.com/learn-en/'

# Repository
repo_name: 'Microbit'
repo_url: 'https://github.com/elecfreaks/learn-en'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 ElecFreaks'

# Theme directory
theme_dir: material

# Icon
#site_favicon: 'docs/images/favicon.ico'
site_favicon: https://raw.githubusercontent.com/elecfreaks/learn-en/master/docs/images/favicon.ico

# Configuration
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: light green
    accent: 'indigo'    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/elecfreaks/learn-en'
    - type: 'facebook'
      link: 'https://www.facebook.com/ElecFreaksTech/'
    #- type: 'linkedin'
    #  link: 'https://linkedin.com/in/squidfunk'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.keys

# Page tree
pages:
  - ElecFreaks Learn: 'index.md'
  
  - Micro:bit Basic Tutorial:
    - BBC micro:bit: micro_bit.md
    - Micro:bit Funny Classroom Series:
        - Flashing Heart: classroom_case_01.md
        - Smiley Buttons: classroom_case_02.md
        - Love Meter: classroom_case_03.md
        - Rock Papaer Scissors: classroom_case_04.md
        - Magic Button Trick: classroom_case_05.md
        - Coin Flipper: classroom_case_06.md
        - Salute: classroom_case_07.md
        - Hack your headphones: classroom_case_08.md
        - Banana Keyboard: classroom_case_09.md
        - Guitar: classroom_case_10.md
        - Duct Type Wallet: classroom_case_11.md
        - Watch: classroom_case_12.md
        - Countdown Timer: classroom_case_13.md
        - Digital Watch: classroom_case_14.md
        - Soil Moisture: classroom_case_15.md
        - Plant Watering: classroom_case_16.md
        - Reaction Time: classroom_case_17.md
        - States of Matter: classroom_case_18.md
        - Mood Radio: classroom_case_19.md
        - Tele-Potato: classroom_case_20.md
        - Hot or Cold: classroom_case_21.md
        - Voting Machine: classroom_case_22.md
        - Infection: classroom_case_23.md
        - Fireflies: classroom_case_24.md
        - Rock Paper Scissors Teams: classroom_case_25.md
        - Microcoin: classroom_case_26.md
        - Inchworm: classroom_case_27.md
        - Milk Monster: classroom_case_28.md
        - RC Car: classroom_case_29.md
        - Timing Gates: classroom_case_30.md
        - Compass: classroom_case_31.md
        - Telegraph: classroom_case_32.md
        - Railway Crossing: classroom_case_33.md
        - Karel: classroom_case_34.md
    - Micro:bit Technology Blog:
        - How to Use Bluetooth(IOS System): How_to_Use_Bluetooth_IOS_System.md
        
  

  - Micro:bit Kits:
     - micro:bit Watch Kit:
          - Watch Kit Introduction: watch_kit.md
          - Power:bit Introduction: power_bit.md
          - Case 01：Compass: watch_kit_case_01.md
          - Case 02：Dice: watch_kit_case_02.md
          - Case 03：Thermometer: watch_kit_case_03.md
          - Case 04：Timer: watch_kit_case_04.md
          - Case 05：Flashlight: watch_kit_case_05.md
          
     - micro:bit basic kit:
          - Basic Kit Introduction: basic_kit.md
          - Basic:bit Introduction: basic_bit.md
          - Case_01 Light Controller: basic_kit_case_01.md
          - Case_02 Morse Code: basic_kit_case_02.md
          - Case_03 Function Selector: basic_kit_case_03.md
          
     - Micro:bit Starter Kit:
          - micro:bit Starter Kit: starter_kit.md
          - Breadboard:bit Introduction: breadboard_bit.md
          - Lesson_01 LED: starter_kit_case_01.md
          - Lesson_02 Button: starter_kit_case_02.md
          - Lesson_03 Trimpot: starter_kit_case_03.md
          - Lesson_04 Photocell: starter_kit_case_04.md
          - Lesson_05 RGB LED: starter_kit_case_05.md
          - Lesson_06 Self-lock Switch: starter_kit_case_06.md
          - Lesson_07 Temperature Sensor: starter_kit_case_07.md
          - Lesson_08 Servo: starter_kit_case_08.md
          - Lesson_09 Buzzer: starter_kit_case_09.md
          - Lesson_10 Motor: starter_kit_case_10.md
          - Lesson_11 Rainbow LED: starter_kit_case_11.md
          - Lesson_12 Accelerometer: starter_kit_case_12.md
          - Lesson_13 Compass: starter_kit_case_13.md
          - Lesson_14 Ambient Light: starter_kit_case_14.md
          
     - Micro:bit Tinker Kit: 
          - Micro:bit Tinker Kit: tinker_kit.md
          - Octopus:bit Introduction: octopus_bit.md
          - Case_01 Music Machine: tinker_kit_case_01.md
          - Case_02 Smart Light: tinker_kit_case_02.md
          - Case_03 Electro-Theremin: tinker_kit_case_03.md
          - Case_04 Simple Alarm Box: tinker_kit_case_04.md
          - Case_05 Plant Monitoring Device: tinker_kit_case_05.md
          - Case_06 Intruder Detection: tinker_kit_case_06.md
          - Case_07 Fish Feeder: tinker_kit_case_07.md
          - Case_08 Motion Detector: tinker_kit_case_08.md
          - Case_09 Lie Detector: tinker_kit_case_09.md
          - Case_10 PADDLEBALLSUPERSMASHEM: tinker_kit_case_10.md
          - Case_11 Avoid Asteroids: tinker_kit_case_11.md
          - Case_12 Remote Control Everything: tinker_kit_case_12.md
          - Case_13 micro:bit Car: tinker_kit_case_13.md
          - Case_14 Flipping Pancakes: tinker_kit_case_14.md
          - Case_15 Maze Runner: tinker_kit_case_15.md
          - Case_16 QUICK MATHS: tinker_kit_case_16.md
          - Case_17 Pitch Perfect: tinker_kit_case_17.md
          - Case_18 Finger Dexterity: tinker_kit_case_18.md
          - Case_19 Electric Spirit Level: tinker_kit_case_19.md
          - Case_20 Space Shooter: tinker_kit_case_20.md
          - Case_21 Flappy Bird: tinker_kit_case_21.md
          - Case_22 Wire Transmission: tinker_kit_case_22.md
          - Case_23 Snake Game: tinker_kit_case_23.md
          
     - Ring:bit Car Kit: 
          - Ring:bit Car Kit: ring_bit_car.md
          - Ring:bit Introduction: ring_bit.md
          - Case_01 Add Package: ring_bit_car_case_01.md
          - Case_02 S Walk: ring_bit_car_case_02.md
          - Case_03 Draw a Circel: ring_bit_car_case_03.md
          - Case_04 Wireless Remote Control: ring_bit_car_case_04.md
          
     - Motor:bit Smart Car Kit: 
          - Motor:bit Smart Car Kit: motor_bit_smart_car.md
          - Motor:bit Introduction: motor_bit_v16.md
          - Case 01 Fixed Parking: motor_bit_smart_car_case_01.md
          - Case 02 Keep Distance: motor_bit_smart_car_case_02.md
          - Case 03 Line Tracking: motor_bit_smart_car_case_03.md
          - Case 04 Avoid Barrier: motor_bit_smart_car_case_04.md
          - Case 05 Remote Control: motor_bit_smart_car_case_05.md
          - Case 06 Bluetooth Control: motor_bit_smart_car_case_06.md
          
  - Micro:bit Modules and Sensor:
    - Sensor:bit: sensor_bit.md
    - Robit: 
          - Robit_Introduction: robit.md
          - Case_01 Ultrasonic Distance Measurement: robit_case_01.md
          - Case_02 Ultrasonic Obstacle Avoidance: robit_case_02.md
          - Case_03 Never Fallen Car: robit_case_03.md
          - Case_04 Line Tracking: robit_case_04.md
          - Case_05 Reversing Alarm: robit_case_05.md
          - Case_06 Rainbow LED: robit_case_06.md
          - Case_07 Smart Car Light: robit_case_07.md
    - Edge:bit: edge_bit.md
    - Joystick:bit: joystick_bit.md
    - Micro:bit Power Supply: microbit_power_supply.md
    - Sonar:bit: sonar_bit.md
    - Octopus Analog Rotation Brick-Blue: octopus_ef04085.md
    - 3V Relay Module: octopus_ef04086.md
    - BME280 Air Pressure Sensor: octopus_ef04087.md
    - Octopus 2 Channel Tracking Module: octopus_ef04088.md     
          

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
